# Generated by Django 5.2.5 on 2025-10-14 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nights_out',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='crowd_atmosphere',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ideal_vibes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='music_preferences',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crowd_atmosphere',
            field=models.ManyToManyField(blank=True, help_text="The user's preferred crowd atmosphere.", related_name='user_profiles_crowds', to='owner.crowdatmosphere'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ideal_vibes',
            field=models.ManyToManyField(blank=True, help_text="The user's preferred ideal vibes.", related_name='user_profiles_vibes', to='owner.vibe'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='music_preferences',
            field=models.ManyToManyField(blank=True, help_text="The user's preferred music genres.", related_name='user_profiles', to='owner.musicgenre'),
        ),
    ]
