# Generated by Django 5.2.5 on 2025-10-08 09:59

import owner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_clubowner_is_active_alter_clubowner_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='ageRequirement',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='clubImageUrl',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='club_type',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='coverCharge',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='dressCode',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='events',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='features',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='practicalInfo',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='vibes_type',
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='weekly_hours',
            field=models.JSONField(default=owner.models.get_default_weekly_hours),
        ),
    ]
