# Generated by Django 5.2.5 on 2025-10-15 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_userprofile_city_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='contact',
        ),
    ]
