# Generated by Django 5.2.5 on 2025-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_remove_clubprofile_agerequirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='weekly_hours',
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='ageRequirement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='clubImageUrl',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='clubs/images/'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='club_type',
            field=models.ManyToManyField(blank=True, to='owner.clubtype'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='contact',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='coverCharge',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='dressCode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='events',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='practicalInfo',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='vibes_type',
            field=models.ManyToManyField(blank=True, to='owner.vibes_choice'),
        ),
    ]
