# Generated by Django 5.2.5 on 2025-10-08 10:01

import owner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_remove_clubprofile_weekly_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='weekly_hours',
            field=models.JSONField(default=owner.models.get_default_weekly_hours),
        ),
    ]
