# Generated by Django 5.2.5 on 2025-10-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_remove_clubprofile_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubprofile',
            old_name='practicalInfo',
            new_name='crowd_atmosphere',
        ),
    ]
