# Generated by Django 5.2.5 on 2025-10-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
