# Generated by Django 5.2.5 on 2025-10-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_rename_practicalinfo_clubprofile_crowd_atmosphere'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
