# Generated by Django 5.2.5 on 2025-10-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='reviews',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
