# Generated by Django 5.2.5 on 2025-10-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_clubprofile_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
