# Generated by Django 5.2.5 on 2025-10-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_clubprofile_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubowner',
            name='venue_address',
        ),
    ]
