# Generated by Django 5.2.5 on 2025-10-11 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_clubprofile_reviews_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.user'),
        ),
    ]
