# Generated by Django 5.2.5 on 2025-10-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_clubprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='user',
        ),
    ]
