# Generated by Django 5.2.5 on 2025-10-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_remove_clubowner_venue_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubowner',
            name='link',
        ),
        migrations.AddField(
            model_name='clubowner',
            name='proof_doc',
            field=models.FileField(default='upload file', upload_to='proofs/images/'),
        ),
    ]
