# Generated by Django 5.2.5 on 2025-10-11 08:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_remove_clubprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_preferences', models.JSONField(blank=True, default=list)),
                ('ideal_vibes', models.JSONField(blank=True, default=list)),
                ('crowd_atmosphere', models.JSONField(blank=True, default=list)),
                ('nights_out', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='owner.user')),
            ],
        ),
    ]
