# Generated by Django 5.2.5 on 2025-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_remove_clubowner_link_clubowner_proof_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='about',
            field=models.TextField(default='write about', max_length=5000),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='insta_link',
            field=models.CharField(default='insta link', max_length=2000),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='tiktok_link',
            field=models.CharField(default='tiktok link', max_length=2000),
        ),
    ]
