# Generated by Django 5.2.5 on 2025-10-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_clubprofile_about_clubprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
