# Generated by Django 5.2.5 on 2025-10-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_userprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='club_location',
            field=models.CharField(default='write city', max_length=100),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
