# Generated by Django 5.2.5 on 2025-10-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_clubprofile_club_location_clubprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubowner',
            name='profile_image',
        ),
    ]
