# Generated by Django 5.2.5 on 2025-10-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_remove_clubowner_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='clubName',
        ),
        migrations.AlterField(
            model_name='clubowner',
            name='proof_doc',
            field=models.FileField(default='upload f ile', upload_to='proofs/images/'),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_profile', to='owner.clubowner'),
        ),
    ]
