# Generated by Django 5.2.5 on 2025-10-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_remove_clubprofile_clubname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='venue_city',
            field=models.CharField(default='write city', max_length=100),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='venue_name',
            field=models.CharField(default='club_name', max_length=255),
        ),
    ]
