# Generated by Django 5.2.5 on 2025-10-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0015_clubprofile_venue_city_clubprofile_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubowner',
            name='profile_image',
            field=models.FileField(default='profile-image', upload_to='profile/images/'),
        ),
        migrations.AlterField(
            model_name='clubowner',
            name='proof_doc',
            field=models.FileField(default='upload file', upload_to='proofs/images/'),
        ),
    ]
