# Generated by Django 5.2.5 on 2025-10-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_clubowner_profile_image_alter_clubowner_proof_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_img',
            field=models.FileField(default='profile-image', upload_to='profile/images/'),
        ),
    ]
