# Generated by Django 5.2.5 on 2025-10-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0017_userprofile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(default='profile-image', upload_to='profile/images/'),
        ),
    ]
