# Generated by Django 5.2.5 on 2025-10-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0019_alter_userprofile_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(blank=True, default='profile/images/default_user.jpg', null=True, upload_to='profile/images/user/'),
        ),
    ]
