# Generated by Django 5.2.5 on 2025-10-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0020_userprofile_achievement_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
