# Generated by Django 5.2.5 on 2025-10-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0021_clubprofile_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='write des'),
        ),
    ]
