# Generated by Django 5.2.5 on 2025-10-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0022_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reviews',
            field=models.JSONField(default=list),
        ),
    ]
