# Generated by Django 5.2.5 on 2025-10-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0023_userprofile_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubprofile',
            old_name='reviews',
            new_name='user_reviews',
        ),
    ]
