# Generated by Django 5.2.5 on 2025-10-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0024_rename_reviews_clubprofile_user_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='reviews',
            new_name='user_reviews',
        ),
    ]
