# Generated by Django 5.2.5 on 2025-11-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0026_userlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='club_location',
        ),
    ]
