# Generated by Django 5.2.7 on 2025-11-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0028_event_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nightclub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('place_id', models.CharField(max_length=200, unique=True)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('osm_raw', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
