# Generated by Django 5.2.7 on 2025-11-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0029_nightclub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nightclub',
        ),
    ]
