# Generated by Django 5.2.7 on 2025-12-11 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0031_nightclub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubowner',
            old_name='venue_city',
            new_name='venue_address',
        ),
    ]
