# Generated by Django 5.2.7 on 2025-12-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0032_rename_venue_city_clubowner_venue_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='venue_city',
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='venue_address',
            field=models.CharField(default='write address', max_length=100),
        ),
    ]
