# Generated by Django 5.2.7 on 2025-12-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0033_remove_clubprofile_venue_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubowner',
            name='venue_address',
            field=models.CharField(default='write address', max_length=100),
        ),
    ]
