# Generated by Django 5.2.7 on 2025-12-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_club', '0003_club_photo_url'),
        ('owner', '0034_alter_clubowner_venue_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubowner',
            name='assigned_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='all_club.club'),
        ),
    ]
