# Generated by Django 5.2.7 on 2025-12-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0036_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
