# Generated by Django 5.2.7 on 2025-12-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0039_alter_userprofile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubowner',
            name='assigned_club',
        ),
    ]
