# Generated by Django 5.2.7 on 2025-12-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0040_remove_clubowner_assigned_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='club',
        ),
    ]
