# Generated by Django 5.2.7 on 2025-12-28 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0041_remove_attendance_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_club.club'),
        ),
        migrations.AddField(
            model_name='clubowner',
            name='assigned_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='all_club.club'),
        ),
    ]
