# Generated by Django 5.2.7 on 2025-12-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_club', '0010_alter_club_club_type'),
        ('owner', '0042_attendance_club_clubowner_assigned_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_clubs',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='all_club.club'),
        ),
    ]
