# Generated by Django 5.2.5 on 2025-10-22 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0016_clubowner_profile_image_alter_clubowner_proof_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('stripe_coupon_id', models.CharField(blank=True, max_length=255, null=True)),
                ('percent_off', models.PositiveIntegerField(default=0)),
                ('duration_in_months', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('stripe_monthly_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_yearly_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('yearly_price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('max_live_events', models.IntegerField(blank=True, null=True)),
                ('admin_seats', models.IntegerField(default=1)),
                ('boost_credits_per_month', models.IntegerField(default=0)),
                ('leads_enabled', models.BooleanField(default=False)),
                ('heatmap_level', models.CharField(choices=[('none', 'None'), ('lite', 'Lite'), ('pro', 'Pro')], default='none', max_length=20)),
                ('analytics_level', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='basic', max_length=20)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('canceled', 'Canceled'), ('trialing', 'Trialing'), ('past_due', 'Past Due')], default='inactive', max_length=50)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('boost_credits_left', models.IntegerField(default=0)),
                ('admin_seats_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='owner.clubowner')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
