# Generated by Django 5.2.5 on 2025-10-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='description',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='key',
            new_name='plan_type',
        ),
    ]
