# Generated by Django 5.2.5 on 2025-10-25 08:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_description_plan_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(default='succeeded', max_length=50)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-paid_at'],
            },
        ),
    ]
