# Generated by Django 5.2.7 on 2025-12-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('category_ids', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('foursquare_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hours', models.TextField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('is_nightlife', models.BooleanField(blank=True, null=True)),
                ('last_fsq_refresh', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('price_level', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('social_media', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('lat_1', models.FloatField(blank=True, null=True)),
                ('lng_1', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
