# Generated by Django 5.2.7 on 2025-12-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_club', '0002_alter_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
