# Generated by Django 5.2.7 on 2025-12-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_club', '0003_club_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
