# Generated by Django 5.2.7 on 2025-12-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_club', '0004_club_name_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='crowd_atmosphere',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='club',
            name='ideal_vibes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='club',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='music_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='club',
            name='user_reviews',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
