# Generated by Django 5.2.7 on 2025-12-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_club', '0005_club_club_type_club_crowd_atmosphere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cover_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
