# Generated by Django 5.2.7 on 2025-12-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_club', '0006_club_cover_charge_club_email_club_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_type',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
