# Generated by Django 5.2.7 on 2025-12-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_club', '0008_alter_club_club_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_type',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
